const SibApiV3Sdk = require('sib-api-v3-sdk');

class BrevoService {
    constructor() {
        // Check if API key is configured
        if (!process.env.BREVO_API_KEY || process.env.BREVO_API_KEY === 'your_brevo_api_key_here') {
            console.warn('⚠️  Brevo API key not configured. Email functionality will be disabled.');
            this.isConfigured = false;
            return;
        }

        try {
            // Configure API key authorization
            const defaultClient = SibApiV3Sdk.ApiClient.instance;
            const apiKey = defaultClient.authentications['api-key'];
            apiKey.apiKey = process.env.BREVO_API_KEY;

            // Initialize Brevo API client
            this.apiInstance = new SibApiV3Sdk.TransactionalEmailsApi();
            this.isConfigured = true;
            console.log('✅ Brevo API initialized successfully');
        } catch (error) {
            console.error('❌ Failed to initialize Brevo API:', error.message);
            this.isConfigured = false;
        }
    }

    async sendLeadEmail(leadData) {
        try {
            // Check if Brevo is configured
            if (!this.isConfigured) {
                console.log('📧 Brevo not configured - logging lead data instead:', leadData);
                return {
                    success: true,
                    messageId: 'mock-' + Date.now(),
                    message: 'Lead logged (Brevo not configured)'
                };
            }

            const { name, email, phone, website } = leadData;
            
            // Create email content
            const emailContent = `
                <h2>🎯 New Lead from Website Audit Tool</h2>
                
                <div style="background: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
                    <h3 style="color: #2d3748; margin-top: 0;">Lead Information:</h3>
                    <table style="width: 100%; border-collapse: collapse;">
                        <tr>
                            <td style="padding: 8px 0; font-weight: bold; color: #4a5568;">Name:</td>
                            <td style="padding: 8px 0; color: #2d3748;">${name}</td>
                        </tr>
                        <tr>
                            <td style="padding: 8px 0; font-weight: bold; color: #4a5568;">Email:</td>
                            <td style="padding: 8px 0; color: #2d3748;">${email}</td>
                        </tr>
                        <tr>
                            <td style="padding: 8px 0; font-weight: bold; color: #4a5568;">Phone:</td>
                            <td style="padding: 8px 0; color: #2d3748;">${phone}</td>
                        </tr>
                        <tr>
                            <td style="padding: 8px 0; font-weight: bold; color: #4a5568;">Website:</td>
                            <td style="padding: 8px 0; color: #2d3748;">${website}</td>
                        </tr>
                    </table>
                </div>

                <div style="background: #e6fffa; padding: 15px; border-radius: 8px; border-left: 4px solid #38b2ac;">
                    <p style="margin: 0; color: #234e52; font-weight: 500;">
                        🚀 This lead completed a website audit and is interested in SEO optimization services.
                    </p>
                </div>

                <div style="margin-top: 20px; padding: 15px; background: #f7fafc; border-radius: 8px;">
                    <p style="margin: 0; color: #4a5568; font-size: 14px;">
                        <strong>Next Steps:</strong><br>
                        • Follow up within 24 hours<br>
                        • Offer personalized SEO consultation<br>
                        • Provide detailed audit report<br>
                        • Discuss optimization strategies
                    </p>
                </div>

                <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;">
                
                <p style="color: #718096; font-size: 12px; margin: 0;">
                    This email was automatically generated by the Website Audit Tool.<br>
                    Timestamp: ${new Date().toLocaleString()}
                </p>
            `;

            // Create email object
            const sendSmtpEmail = new SibApiV3Sdk.SendSmtpEmail();
            sendSmtpEmail.subject = `🎯 New Lead: ${name} - Website Audit Tool`;
            sendSmtpEmail.htmlContent = emailContent;
            sendSmtpEmail.sender = {
                name: "Website Audit Tool",
                email: process.env.BREVO_SENDER_EMAIL || "noreply@optimizemydata.com"
            };
            sendSmtpEmail.to = [
                {
                    email: "manu@optimizemydata.com",
                    name: "Manu"
                }
            ];

            // Add reply-to as the lead's email for easy response
            sendSmtpEmail.replyTo = {
                email: email,
                name: name
            };

            // Send email
            console.log('📧 Attempting to send lead email to manu@optimizemydata.com...');
            console.log('📧 Email details:', {
                to: 'manu@optimizemydata.com',
                from: process.env.BREVO_SENDER_EMAIL,
                subject: `🎯 New Lead: ${name} - Website Audit Tool`
            });
            
            const result = await this.apiInstance.sendTransacEmail(sendSmtpEmail);
            
            console.log('✅ Lead email sent successfully:', {
                messageId: result.messageId,
                leadName: name,
                leadEmail: email,
                website: website
            });

            return {
                success: true,
                messageId: result.messageId,
                message: 'Lead email sent successfully'
            };

        } catch (error) {
            console.error('❌ Error sending lead email:', error);
            throw new Error(`Failed to send lead email: ${error.message}`);
        }
    }

    async sendWelcomeEmail(leadData) {
        try {
            // Check if Brevo is configured
            if (!this.isConfigured) {
                console.log('📧 Brevo not configured - skipping welcome email');
                return {
                    success: true,
                    messageId: 'mock-welcome-' + Date.now(),
                    message: 'Welcome email skipped (Brevo not configured)'
                };
            }

            const { name, email, website } = leadData;
            
            const emailContent = `
                <div style="max-width: 600px; margin: 0 auto; font-family: Arial, sans-serif;">
                    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; color: white;">
                        <h1 style="margin: 0; font-size: 28px;">🚀 Welcome to OptimizeMyData!</h1>
                        <p style="margin: 10px 0 0 0; font-size: 16px; opacity: 0.9;">Thank you for your interest in SEO optimization</p>
                    </div>
                    
                    <div style="padding: 30px; background: white;">
                        <h2 style="color: #2d3748; margin-top: 0;">Hi ${name}! 👋</h2>
                        
                        <p style="color: #4a5568; line-height: 1.6;">
                            Thank you for using our Website Audit Tool and showing interest in optimizing your website 
                            <strong>${website}</strong> for better search engine rankings.
                        </p>
                        
                        <div style="background: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
                            <h3 style="color: #2d3748; margin-top: 0;">What happens next?</h3>
                            <ul style="color: #4a5568; line-height: 1.8;">
                                <li>Our SEO expert will review your audit results</li>
                                <li>We'll prepare a personalized optimization strategy</li>
                                <li>You'll receive a detailed report within 24 hours</li>
                                <li>We'll schedule a free consultation call</li>
                            </ul>
                        </div>
                        
                        <div style="background: #e6fffa; padding: 20px; border-radius: 8px; border-left: 4px solid #38b2ac;">
                            <h3 style="color: #234e52; margin-top: 0;">🎯 Why Choose OptimizeMyData?</h3>
                            <ul style="color: #234e52; line-height: 1.8;">
                                <li>Proven track record of improving search rankings</li>
                                <li>Customized strategies for your business</li>
                                <li>Transparent reporting and communication</li>
                                <li>Competitive pricing with guaranteed results</li>
                            </ul>
                        </div>
                        
                        <div style="text-align: center; margin: 30px 0;">
                            <a href="mailto:manu@optimizemydata.com" 
                               style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                                      color: white; 
                                      padding: 15px 30px; 
                                      text-decoration: none; 
                                      border-radius: 8px; 
                                      font-weight: bold;
                                      display: inline-block;">
                                📧 Contact Us Now
                            </a>
                        </div>
                        
                        <p style="color: #718096; font-size: 14px; text-align: center;">
                            Questions? Reply to this email or call us directly.<br>
                            We're here to help your business grow! 🌟
                        </p>
                    </div>
                    
                    <div style="background: #f7fafc; padding: 20px; text-align: center; color: #718096; font-size: 12px;">
                        <p style="margin: 0;">
                            OptimizeMyData | Professional SEO Services<br>
                            Email: manu@optimizemydata.com
                        </p>
                    </div>
                </div>
            `;

            const sendSmtpEmail = new SibApiV3Sdk.SendSmtpEmail();
            sendSmtpEmail.subject = `🚀 Welcome ${name}! Let's Optimize Your Website`;
            sendSmtpEmail.htmlContent = emailContent;
            sendSmtpEmail.sender = {
                name: "OptimizeMyData Team",
                email: process.env.BREVO_SENDER_EMAIL || "noreply@optimizemydata.com"
            };
            sendSmtpEmail.to = [
                {
                    email: email,
                    name: name
                }
            ];

            const result = await this.apiInstance.sendTransacEmail(sendSmtpEmail);
            
            console.log('✅ Welcome email sent successfully:', {
                messageId: result.messageId,
                recipientName: name,
                recipientEmail: email
            });

            return {
                success: true,
                messageId: result.messageId,
                message: 'Welcome email sent successfully'
            };

        } catch (error) {
            console.error('❌ Error sending welcome email:', error);
            throw new Error(`Failed to send welcome email: ${error.message}`);
        }
    }
}

module.exports = BrevoService;
